name: Lint code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.15.2, 1.15.0]

    steps:
      - name: Git Checkout Deno Module
        uses: actions/checkout@v2

      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
		  
      - name: Lint Deno Module
        run: deno fmt --check
	 
      - name: Commit to repo
        run: git add . && git commit -m "Automated lint" && git push -u main
